en:
  languageName: English
  weight: 1

zh-cn:
  languageName: 简体中文
  weight: 4
  params:
    dateFormat: '2006-01-02'
    description: 一个快速、响应式和功能丰富的 Hugo 博客主题
    keywords: 'Hugo, Bootstrap, 博客主题'
    archive:
      dateFormat: 01-02

# add hindi language
hi:
  languageName: हिंदी
  weight: 2
  params:
    dateFormat: '02-01-2006'
    description: एक तेज़, रिस्पॉन्सिव और फ़ीचर रचनात्मक Hugo ब्लॉग थीम
    keywords: 'Hugo, Bootstrap, ब्लॉग थीम'
    archive:
      dateFormat: 02-01
