# See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
email: hello@viralvaghela.com
# facebook: yourfacebookusername
github: viralvaghela
# gitlab: yourgitlabusername
linkedin: viralv
# xing: yourxi  ngusername
stackoverflow: 13090648/viral
twitter: viral_codes
# weibo: yourweibousername
# zhihu: yourzhihuusername
instagram: coding_boy_
# quora: yourquorausername
# tumblr: yourtumblrusername
# reddit: yourredditusername
# telegram: yourtelegramusername
# qq: yourqqnumber
# dockerhub: yourdockerhubusername
# bitbucket: yourbitbucketworkspaceid
# kaggle: yourkaggleusername
medium: https://vaghelaviral.medium.com/ # Medium username or custom domain(e.g. https://custom.domain.tld).
openbugbounty: https://www.openbugbounty.org/researchers/Codingboy/
# lastfm: yourlastfmusername
# bilibili: yourbilibiliuserid
# youtube: youryoutubechannelid
# discord: yourdiscordinvitecode
# discourse: https://yourforum.tld
# facebookgroup: yourfacebookgroupname
# tiktok: yourtiktokusername
# pinterest: yourpinterestusername
# mastodon: yourmastodonusername
# liberapay: yourliberapayaccount
# paypal: razonyang
# patreon: razonyang
# tipeee: yourtipeeeaccount-fr
